import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import QRCode from 'qrcode';
import {
  SITE_URL, SITE_NAME, APP_STORE_URL, PLAY_STORE_URL, SUPPORT_EMAIL,
  APPLE_TEAM_ID, ANDROID_SHA256, COLOR_CPP_ID, TRYON_CPP_ID, CLOSET_CPP_ID,
  LAST_UPDATED
} from '../site.config.mjs';

const root = new URL('..', import.meta.url).pathname;
const out = join(root, 'dist');
const accessed = 'Accessed September 14, 2026';
const allPaths = new Set(['/']);
const sitemapGroups = { pages: [], blog: [], answers: [], glossary: [] };

const esc = (value='') => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const slugify = value => value.toLowerCase().replaceAll('&','and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const url = path => SITE_URL + (path === '/' ? '/' : path.replace(/\/$/,'') + '/');
const ld = graph => '<script type="application/ld+json">' + JSON.stringify({'@context':'https://schema.org','@graph':graph}).replaceAll('<','\\u003c') + '</script>';
const source = (label, href) => '<a class="source" href="' + href + '" rel="nofollow">' + esc(label) + ' <span>' + accessed + '</span></a>';

function storeButtons(page='page') {
  return '<div class="store-row"><a class="store-badge" data-store="apple" data-page="' + page + '" href="' + APP_STORE_URL + '"><span aria-hidden="true">●</span><span><small>Download on the</small>App Store</span></a><a class="store-badge" data-store="google" data-page="' + page + '" href="' + PLAY_STORE_URL + '"><span aria-hidden="true">▶</span><span><small>GET IT ON</small>Google Play</span></a></div>';
}

const nav = '<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="/" aria-label="Style BFF home"><span class="brand-mark">B</span><span>Style BFF</span></a><nav aria-label="Primary navigation"><details class="nav-features"><summary>Features</summary><div class="nav-menu"><a href="/features/daily-outfits-on-you/">Daily outfits</a><a href="/features/color-analysis/">Color analysis</a><a href="/features/body-type/">Body type</a><a href="/features/virtual-try-on/">Virtual try-on</a><a href="/features/try-on-from-pinterest-instagram/">Try links</a><a href="/features/digital-closet/">Digital closet</a><a href="/features/complete-the-closet/">Complete the closet</a></div></details><a href="/how-it-works/">How it works</a><a href="/compare/">Compare</a><a href="/blog/">Blog</a></nav><a class="button button-small" href="/download/">Download</a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-menu">Menu</button></header><div class="mobile-menu" id="mobile-menu" hidden><a href="/features/color-analysis/">Features</a><a href="/how-it-works/">How it works</a><a href="/compare/">Compare</a><a href="/blog/">Blog</a><a href="/download/">Download</a></div>';
const footer = '<footer class="site-footer"><div class="footer-top"><div><a class="brand" href="/"><span class="brand-mark">B</span><span>Style BFF</span></a><p>The stylist who starts with you.</p></div><div><h2>Product</h2><a href="/how-it-works/">How it works</a><a href="/roadmap/">Roadmap</a><a href="/download/">Download</a></div><div><h2>Compare</h2><a href="/compare/">All comparisons</a><a href="/compare/doppl-alternatives/">Doppl alternatives</a><a href="/compare/chatgpt-as-a-stylist/">ChatGPT</a></div><div><h2>Learn</h2><a href="/answers/">Answers</a><a href="/blog/">Blog</a><a href="/glossary/">Glossary</a><a href="/quiz/">Color quiz</a></div><div><h2>Company</h2><a href="/about/">About</a><a href="/press/">Press</a><a href="/support/">Support</a><a href="/bingetry/">BingeTry rename</a></div><div><h2>Legal</h2><a href="/privacy/">Privacy</a><a href="/terms/">Terms</a><a href="/delete-account/">Delete account</a><a href="/sitemap/">Sitemap</a></div></div><div class="footer-bottom"><span>© 2026 Style BFF</span><span>Made in India. Dressing the world.</span></div></footer>';

function baseGraph(page) {
  const graph = [
    {'@type':'Organization','@id':SITE_URL+'/#organization','name':'Style BFF','alternateName':'BingeTry','url':SITE_URL+'/','logo':SITE_URL+'/assets/logo_new.webp','sameAs':[APP_STORE_URL,PLAY_STORE_URL]},
    {'@type':'WebSite','@id':SITE_URL+'/#website','name':'Style BFF','url':SITE_URL+'/','publisher':{'@id':SITE_URL+'/#organization'},'potentialAction':{'@type':'SearchAction','target':SITE_URL+'/blog/?q={search_term_string}','query-input':'required name=search_term_string'}},
    {'@type':'BreadcrumbList','itemListElement':page.path.split('/').filter(Boolean).map((name,index,list)=>({'@type':'ListItem','position':index+1,'name':name.replaceAll('-',' '),'item':SITE_URL+'/'+list.slice(0,index+1).join('/')+'/'}))}
  ];
  if (page.schema) graph.push(page.schema);
  if (page.faq?.length) graph.push({'@type':'FAQPage','mainEntity':page.faq.map(item=>({'@type':'Question','name':item[0],'acceptedAnswer':{'@type':'Answer','text':item[1]}}))});
  return graph;
}

function head(page) {
  const title = page.title.length > 60 ? page.title.slice(0,57) + '…' : page.title;
  const description = page.description.length > 155 ? page.description.slice(0,152) + '…' : page.description;
  const noindex = page.status === 'outline' ? '<meta name="robots" content="noindex,follow" />' : '';
  return '<!doctype html><html lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><title>' + esc(title) + '</title><meta name="description" content="' + esc(description) + '"/><link rel="canonical" href="' + url(page.path) + '"/><link rel="alternate" hreflang="en" href="' + url(page.path) + '"/><link rel="alternate" hreflang="x-default" href="' + url(page.path) + '"/><meta property="og:type" content="website"/><meta property="og:title" content="' + esc(title) + '"/><meta property="og:description" content="' + esc(description) + '"/><meta property="og:url" content="' + url(page.path) + '"/><meta property="og:image" content="' + SITE_URL + '/assets/og-style-bff.png"/><meta name="twitter:card" content="summary_large_image"/><meta name="twitter:title" content="' + esc(title) + '"/><meta name="twitter:description" content="' + esc(description) + '"/><meta name="twitter:image" content="' + SITE_URL + '/assets/og-style-bff.png"/><meta name="apple-itunes-app" content="app-id=6767003047, app-argument=' + url(page.path) + '"/><link rel="alternate" href="android-app://com.bingetry.vitualtryon/https/' + new URL(SITE_URL).hostname + page.path + '"/><link rel="stylesheet" href="/styles.css"/><link rel="stylesheet" href="/pages.css"/><link rel="icon" type="image/svg+xml" href="/favicon.svg"/>' + noindex + '</head><body>';
}

function cta(page) {
  return '<aside class="page-cta"><div><p class="eyebrow">Your next outfit</p><h2>See it on you.</h2><p>Search <strong>Style BFF</strong> on the App Store or Google Play.</p>' + storeButtons(slugify(page.h1)) + '</div><a class="qr-placeholder" href="/download/" aria-label="Open the Style BFF download page"><img src="/assets/qr-download.png" width="168" height="168" alt="QR code for the Style BFF download page"/></a></aside>';
}

function sectionMarkup(sections=[]) {
  return sections.map(item => '<section class="article-section"><h2>' + esc(item[0]) + '</h2>' + (Array.isArray(item[1]) ? '<ul>' + item[1].map(x=>'<li>'+x+'</li>').join('') + '</ul>' : '<p>' + item[1] + '</p>') + '</section>').join('');
}

function faqMarkup(faq=[]) {
  if (!faq.length) return '';
  return '<section class="article-section"><h2>What else should you know?</h2><div class="faq-list">' + faq.map(item=>'<details><summary>'+esc(item[0])+'</summary><p>'+item[1]+'</p></details>').join('') + '</div></section>';
}

function pageBody(page) {
  const image = page.image ? '<figure class="page-visual"><img src="' + page.image + '" alt="' + esc(page.imageAlt || page.h1) + '" width="1024" height="1024"/></figure>' : '';
  const badge = page.status === 'outline' ? '<span class="status-badge">Editorial outline</span>' : '';
  const extra = page.html || '';
  return nav + '<main id="main"><article class="page-shell"><header class="page-hero"><div><p class="eyebrow">' + esc(page.kicker || page.primaryKeyword || 'Style BFF guide') + '</p>' + badge + '<h1>' + esc(page.h1) + '</h1><p class="answer-first">' + page.answer + '</p><p class="updated">Last updated ' + LAST_UPDATED + '</p>' + storeButtons(slugify(page.h1)) + '</div>' + image + '</header><div class="article-body">' + (page.cite ? '<aside class="cite-block">' + page.cite + '</aside>' : '') + sectionMarkup(page.sections) + extra + faqMarkup(page.faq) + '</div>' + cta(page) + '</article></main>' + footer + ld(baseGraph(page)) + '<script src="/site.js" defer></script></body></html>';
}

async function writeRoute(page, group='pages') {
  const clean = page.path === '/' ? '' : page.path.replace(/^\/|\/$/g,'');
  const file = clean ? join(out, clean, 'index.html') : join(out, 'index.html');
  await mkdir(dirname(file), {recursive:true});
  await writeFile(file, page.path === '/' ? page.html : head(page) + pageBody(page), 'utf8');
  allPaths.add(page.path);
  if (page.status !== 'outline' && !page.noSitemap) sitemapGroups[group].push(page.path);
}

const commonFaq = [
  ['Is Style BFF free?', 'Your Style Profile is free and does not require a card.'],
  ['Does Style BFF work on Android?', 'Yes. Style BFF is available on iOS and Android.'],
  ['Can I use clothes I already own?', 'Yes. Add items to your digital closet and ask your BFF to build combinations from them.']
];

const featurePages = [
  ['/features/daily-outfits-on-you/','What to Wear Today App | Style BFF','See today’s outfit on you, every morning','what to wear today app','Your BFF combines your weather, plans, palette and closet to create a daily outfit, then renders it on your photo so you can decide fast.','/assets/ss_stylist.webp',[['How does the daily outfit work?','Open the app each morning to see a look matched to your profile and the context you share.'],['What makes the recommendation personal?','Color harmony, proportion, occasion and your saved preferences shape the result.'],['Can you change the look?','Try a different direction or swap individual pieces before you get dressed.']]],
  ['/features/color-analysis/','Color Analysis App | Style BFF','Free AI color analysis from one selfie','color analysis app','A free Style Profile identifies your 12-season color palette from one clear selfie and turns the result into practical outfit guidance.','/assets/app_screenshot_trending.webp',[['What does the free profile include?','Your season, a personal palette and three rules you can apply while dressing.'],['How should you take the selfie?','Use indirect daylight, remove color filters and keep your face unobstructed.'],['What should you do with your palette?','Use it to compare tops, accessories and outfit combinations in the app.']]],
  ['/features/body-type/','Body Type Calculator | Style BFF','Find your body type and what flatters it','body type calculator','Your Style Profile reads proportion cues and explains which silhouettes create the balance you want without treating your body as a problem to fix.','/assets/ss_stylist.webp',[['How is body type used?','Style BFF uses proportion as one styling input alongside color, occasion and preference.'],['Is this a body rulebook?','No. The result is a set of options, not a list of restrictions.'],['Can plus-size users use it?','The feature is designed around proportion rather than a single sample size. Broader model coverage should be verified by the founder before launch.']]],
  ['/features/virtual-try-on/','Virtual Try On Clothes | Style BFF','Try any look on yourself before you buy','virtual try on clothes','Style BFF turns an outfit or garment into a visual try-on on your own photo, so you can judge the whole look before wearing or buying it.','/assets/phone_mockup_tryon.webp',[['What can virtual try-on show?','It helps you compare color, proportion and the overall direction of a look on your photo.'],['Is the render exact?','No virtual try-on is a guarantee of fit, fabric behavior or garment detail. Use it as a styling preview.'],['Can you save a look?','Save useful results in the app so you can return to them while dressing or shopping.']]],
  ['/features/try-on-from-pinterest-instagram/','Try On Pinterest Outfits | Style BFF','Saw it on Pinterest? Try it on you.','try on pinterest outfit','Share a Pinterest, Instagram or store product link with Style BFF and turn the inspiration into a try-on on your own photo.','/assets/phone_mockup_discover.webp',[['How do link try-ons work?','Copy or share a supported link to Style BFF. The app reads the visible outfit and creates a personal preview.'],['Which links can you use?','Pinterest, Instagram and many public product pages are supported; private or blocked posts may not import.'],['Can you use your own clothes?','Yes. Use the inspiration as a direction, then rebuild it from your digital closet.']]],
  ['/features/digital-closet/','Digital Closet App | Style BFF','Your closet, finally styled','digital closet app','Style BFF keeps your owned clothes in one visual closet and combines them into daily and occasion outfits matched to your profile.','/assets/ss_lookbook.webp',[['What belongs in your digital closet?','Add the pieces you wear or want to use more. You do not need to catalogue every sock before getting value.'],['What does the BFF do with your closet?','It builds combinations, plans occasion outfits and connects pieces to your color and proportion rules.'],['Can you add your own clothes?','Yes. Your real wardrobe is the starting point.']]],
  ['/features/complete-the-closet/','Wardrobe Gap Finder | Style BFF','Buy the 3 pieces that unlock 20 outfits','what to buy for my wardrobe','Complete the Closet studies what you own and finds the two or three additions that could create the most useful new combinations.','/assets/app_screenshot_garment.webp',[['How are wardrobe gaps found?','The feature looks for missing connectors: pieces that work across several existing items and occasions.'],['Does it make a shopping list?','It explains why each suggested piece earns a place and which outfits it could unlock.'],['Will it tell you to replace everything?','No. The goal is to use more of what you already own.']]]
];

const standardPages = [
  {path:'/how-it-works/',title:'How Does an AI Stylist Work? | Style BFF',h1:'How Style BFF dresses you every morning',primaryKeyword:'how does an ai stylist work',description:'See how Style BFF learns your colors and body, styles your closet, and renders a daily outfit on your photo in six clear steps.',answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) turns one selfie and five quick answers into a Style Profile, then uses your closet, weather and plans to show an outfit on you.',image:'/assets/fashion_editorial.webp',sections:[['How do you start?',['1. Take a clear selfie.','2. Answer five questions about your style and life.','3. Review your free Style Profile.']],['How does your daily loop work?',['4. Add clothes you want to wear more.','5. Open a daily outfit rendered on you.','6. Try saved, shared or shoppable looks before deciding.']]],schema:{'@type':'HowTo','name':'How Style BFF dresses you every morning','step':['Take a selfie','Answer five questions','Review your Style Profile','Add your clothes','Open today’s outfit','Try another look'].map((name,i)=>({'@type':'HowToStep','position':i+1,'name':name}))}},

  {path:'/about/',title:'Style BFF Founders | Style BFF',h1:'Two founders, one closet problem',primaryKeyword:'style bff founders',description:'Learn why the founders created Style BFF in India to make useful personal styling available on a phone around the world.',answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) was built in India around a familiar problem: a full closet, a real day ahead and no clear answer about what to wear.',sections:[['Why did we build Style BFF?','We wanted personal styling to begin with the person and the clothes they already own, not another shopping feed.'],['Who built it?','Founder names, bios and headshots are awaiting founder approval. This page deliberately does not invent them.'],['Why India to the world?','Style BFF is being built in India for women getting dressed across the US, UK, Canada, Australia and beyond.']],status:'published'},
  {path:'/press/',title:'Style BFF Press Kit | Style BFF',h1:'Press & facts',primaryKeyword:'style bff press kit',description:'Find verified Style BFF facts, pricing, platform links, product language, screenshots, and guidance for accurate press coverage.',answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) learns a user’s colors and body, styles clothes she owns and renders daily or shared outfits on her own photo.',sections:[['What are the facts about Style BFF?','Use the table below for plain, quotable facts. Blank founder fields are clearly marked instead of inferred.'],['How should you cite Style BFF?','“Style BFF is an AI personal stylist app for iOS and Android that renders daily outfits on the user’s own photo.”'],['Which assets can press use?','Current product screenshots are available on this site. Approved logo files, founder headshots and a complete media-use license remain founder-supplied items.']],html:'<div class="table-wrap"><table><caption>Facts about Style BFF</caption><tbody><tr><th>Name</th><td>Style BFF (formerly BingeTry)</td></tr><tr><th>Founded</th><td>Awaiting founder approval</td></tr><tr><th>Headquarters</th><td>India; city awaiting founder approval</td></tr><tr><th>Platforms</th><td>iOS and Android</td></tr><tr><th>Price</th><td>Free Style Profile</td></tr><tr><th>Languages</th><td>Awaiting founder approval</td></tr><tr><th>Features</th><td>Style Profile, daily outfits on your photo, link try-on, digital closet, Complete the Closet</td></tr><tr><th>What it replaces</th><td>Daily outfit guessing across separate palette, closet and try-on tools</td></tr></tbody></table></div>'},
  {path:'/roadmap/',title:'Style BFF Roadmap | Style BFF',h1:'What’s coming to your BFF',primaryKeyword:'style bff roadmap',description:'See which Style BFF features are available today and which ideas are clearly marked as coming soon.',answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) is live for daily outfits, link try-on, digital closet and Complete the Closet. Hair, makeup and jewelry matching are coming soon.',sections:[['What is live now?',['Daily outfits rendered on you','Try a look from a link','Digital closet combinations','Complete the Closet recommendations']],['What is coming soon?',['Hair matched to your palette','Makeup direction','Jewelry matched to your palette','Home widget and outfit streak: status awaiting founder confirmation']],['How are roadmap items described?','A roadmap item is not presented as live until it ships. Timing can change.']]},
  {path:'/bingetry/',title:'BingeTry App Is Now Style BFF | Style BFF',h1:'BingeTry is now Style BFF',primaryKeyword:'bingetry app',description:'Learn why BingeTry became Style BFF, what changed, and where existing iOS and Android users can find the same app.',answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) is the new name for BingeTry. The rename puts the product’s real job—being your personal stylist—at the center.',sections:[['Why did BingeTry change its name?','BingeTry started with virtual try-on. The product grew into daily styling, color and proportion guidance, a digital closet and practical shopping decisions.'],['Is it the same app?','Yes. Existing store IDs remain the destination during the rename.'],['Do you need a new account?','No account migration claim is published until the founder confirms the exact release behavior.']]},
  {path:'/support/',title:'Style BFF Support | Style BFF',h1:'Support',primaryKeyword:'style bff support',description:'Contact Style BFF support, manage an iOS or Android subscription, and find clear account-deletion instructions.',answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) support is available at '+SUPPORT_EMAIL+'. Billing is managed by the store where you subscribed.',sections:[['How do you contact support?','Email <a href="mailto:'+SUPPORT_EMAIL+'">'+SUPPORT_EMAIL+'</a> with the device type and a short description. Do not email sensitive photos or payment details.'],['How do you manage an iOS subscription?','Open iPhone Settings, tap your name, choose Subscriptions, then select Style BFF.'],['How do you manage an Android subscription?','Open Google Play, tap your profile, choose Payments & subscriptions, then Subscriptions.']],faq:[['Where are refunds handled?','Apple and Google apply their own refund policies to purchases made through their stores.'],['How do I delete my account?','Follow the delete-account page or use the account controls in the app.']]},
  {path:'/delete-account/',title:'Delete Style BFF Account | Style BFF',h1:'Delete your account',primaryKeyword:'delete style bff account',description:'Follow the steps to request deletion of your Style BFF account and associated personal information.',answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) lets you request account deletion from the app or by email. Deletion steps are listed below.',sections:[['How do you delete your account in the app?',['1. Open Style BFF.','2. Open your profile and account settings.','3. Choose Delete account.','4. Review the warning and confirm.']],['What if you cannot open the app?','Email <a href="mailto:'+SUPPORT_EMAIL+'?subject=Delete%20my%20Style%20BFF%20account">'+SUPPORT_EMAIL+'</a> from the address linked to your account.'],['What happens next?','The exact deletion and retention timeline must be added from the approved privacy policy before launch.']],schema:{'@type':'HowTo','name':'How to delete a Style BFF account','step':['Open the app','Open account settings','Choose Delete account','Confirm the request'].map((name,i)=>({'@type':'HowToStep','position':i+1,'name':name}))}},
  {path:'/privacy/',title:'Privacy Policy | Style BFF',h1:'Privacy policy',primaryKeyword:'style bff privacy',description:'Read the current Style BFF privacy notice and learn where to ask questions about photos, account data, and deletion.',answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) uses photos to provide styling and try-on features. The approved legal policy must replace this launch placeholder before publication.',sections:[['What information does Style BFF process?','Account information, submitted photos, wardrobe images and app activity may be needed to provide requested features. Exact categories await the approved legal policy.'],['Are photos used to train models?','This answer is intentionally left unpublished until the founder and counsel confirm the current data-processing terms.'],['How do you exercise privacy rights?','Contact <a href="mailto:'+SUPPORT_EMAIL+'">'+SUPPORT_EMAIL+'</a>. The final policy must state regional rights, retention, processors and response timelines.']]},
  {path:'/terms/',title:'Terms of Service | Style BFF',h1:'Terms of service',primaryKeyword:'style bff terms',description:'Read the current terms governing Style BFF accounts, subscriptions, virtual try-on output, and acceptable use.',answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) provides styling guidance and visual previews. The approved legal terms must replace this launch placeholder before publication.',sections:[['What do the terms cover?','Accounts, subscriptions, acceptable use, intellectual property, generated output and service availability.'],['Are try-on renders guarantees?','No. A generated preview is not a guarantee of exact fit, color, material or construction.'],['Who handles store billing?','Apple or Google manages purchases, cancellations and store refunds under its policies.']]}
];

const compareData = [
  ['style-bff-vs-whering','Whering','https://www.whering.co/','Whering focuses on organizing, tracking and socially exploring a wardrobe. Style BFF starts from personal analysis and renders recommended outfits on your photo.'],
  ['style-bff-vs-alta','Alta','https://www.altadaily.com/','Alta and Style BFF both style an existing closet. Alta describes try-on with a virtual avatar; Style BFF centers the result on the user’s uploaded photo.'],
  ['style-bff-vs-style-dna','Style DNA','https://apps.apple.com/us/app/style-dna-ai-color-analysis/id1358319821','Style DNA combines color analysis, body guidance, closet tools and shopping. Style BFF adds link-to-try-on and daily outfit renders on your own photo.'],
  ['style-bff-vs-dressly','Dressly','https://apps.apple.com/us/app/dressly-ai-outfit-maker/id6738174180','Dressly offers an AI stylist, outfit ideas and try-on. Style BFF is the clearer fit when daily outfits on your own photo and link-to-try-on are the deciding features.'],
  ['doppl-alternatives','Doppl','https://blog.google/innovation-and-ai/models-and-research/google-labs/doppl/','Google’s experimental Doppl app launched in June 2025 for outfit try-on on a digital version of the user and later closed as a standalone app. Style BFF is one alternative for try-on plus ongoing personal styling.'],
  ['chatgpt-as-a-stylist','ChatGPT','https://help.openai.com/en/articles/12677804-what-is-chatgpt-faq','ChatGPT is flexible for conversation, prompts and image questions. Style BFF is built around a persistent Style Profile, a digital closet and a daily outfit workflow.'],
  ['style-bff-vs-indyx','Indyx','https://www.myindyx.com/','This comparison is an editorial outline until current Indyx pricing, platforms and public feature claims are source-checked.'],
  ['style-bff-vs-acloset','Acloset','https://www.acloset.app/','This comparison is an editorial outline until current Acloset pricing, platforms and public feature claims are source-checked.']
];

const questions = [
  'What is an AI personal stylist?','How does an AI stylist app work?','What is the best AI stylist app?','Is there a free AI stylist app?','How much does a personal stylist cost?','Is an AI stylist better than a human stylist?','What is virtual try-on and how accurate is it?','Can I try on clothes with my own photo?','Can I try on an outfit from Pinterest or Instagram?','What happened to Google Doppl?','What is the best Doppl alternative?','What is seasonal color analysis?','How do I find my color season?','Is AI color analysis accurate?','What are the 12 color seasons?','What is a Kibbe body type?','How do I know my body type?','What is a digital closet app?','What is the best digital closet app?','What is a capsule wardrobe?','How many clothes do I need for a capsule wardrobe?','What is cost per wear?','How do I know if an outfit suits me?','Why do I feel like I have nothing to wear?','What should I wear today?','Does Style BFF work on Android?','How much does Style BFF cost?','Is Style BFF free?','Is my photo safe in Style BFF?','What was BingeTry? Is BingeTry the same as Style BFF?'
];

const directAnswers = {
  'What is an AI personal stylist?':'An AI personal stylist is software that uses information about your appearance, preferences, wardrobe and plans to recommend what to wear. Style BFF adds a visual step by rendering the suggested outfit on your own photo.',
  'How does an AI stylist app work?':'An AI stylist app collects style inputs, analyses patterns such as color and proportion, and ranks outfit choices for a specific person or occasion. The useful test is whether its advice connects to clothes you can actually wear.',
  'What is the best AI stylist app?':'The best AI stylist app depends on your main task. Choose wardrobe tracking for closet statistics, color tools for a palette, or Style BFF when you want analysis, daily outfits and try-on on your own photo in one loop.',
  'Is there a free AI stylist app?':'Yes. Several styling apps offer free tools or tiers. Style BFF makes the Style Profile free, including a 12-season color palette, body type and three personal style rules; ongoing daily styling is part of Plus.',
  'How much does a personal stylist cost?':'A human personal styling session often costs about $100–$400, depending on location, scope and the stylist. App subscriptions are usually lower, but they do not replace the judgment or service of a human professional.',
  'Is an AI stylist better than a human stylist?':'An AI stylist is faster, cheaper and available every morning. A human stylist can bring deeper observation, tailoring and relationship-based judgment. The better choice depends on whether you need daily convenience or high-touch expertise.',
  'What is virtual try-on and how accurate is it?':'Virtual try-on creates a visual estimate of clothing on a person or avatar. It can help compare color and silhouette, but it is not a guarantee of fit, fabric movement, construction or exact garment detail.',
  'Can I try on clothes with my own photo?':'Yes. Style BFF lets you use an uploaded photo to preview an outfit on yourself. Use a clear, well-lit image and treat the result as styling guidance rather than an exact fit prediction.',
  'Can I try on an outfit from Pinterest or Instagram?':'Yes. Share a supported public Pinterest, Instagram or product link to Style BFF to create a try-on on your own photo. Private, deleted or access-restricted posts may not import.',
  'What happened to Google Doppl?':'Google launched Doppl as a US experiment in June 2025 for trying outfits on a digital version of yourself. The standalone app later closed; Google said the underlying virtual try-on technology was moving into its shopping surfaces.'
};

const glossary = ['12 color seasons','13 Kibbe types','color analysis','draping','undertone','chroma','value','body type vs body shape','capsule wardrobe','cost per wear','virtual try-on','garment transfer','digital closet','outfit formula','OOTD','dupe','shop the look'];
const seasons = ['bright-spring','true-spring','light-spring','light-summer','true-summer','soft-summer','soft-autumn','true-autumn','deep-autumn','deep-winter','true-winter','bright-winter'];

function comparisonHtml(name, href) {
  return '<div class="table-wrap"><table><caption>Style BFF and '+esc(name)+' at a glance</caption><thead><tr><th>Question</th><th>Style BFF</th><th>'+esc(name)+'</th></tr></thead><tbody><tr><th>Core job</th><td>Personal profile, daily outfit and try-on</td><td>See current official product description</td></tr><tr><th>Try-on type</th><td>Your uploaded photo</td><td>Verify in current listing</td></tr><tr><th>Closet</th><td>Yes</td><td>Verify in current listing</td></tr><tr><th>Price</th><td>Free Style Profile</td><td>Check current store price</td></tr></tbody></table></div><p>'+source(name+' official product source',href)+'</p>';
}

function quizHtml() {
  const qs = [
    ['veins','Which color do your wrist veins look?',['Blue or purple','Green or olive','A mix or unclear']],
    ['jewelry','Which jewelry usually feels at home?',['Silver','Gold','Both']],
    ['tan','What happens in the sun?',['Burn first','Tan easily','A bit of both']],
    ['eyes','What describes your eye pattern?',['Soft and blended','Clear and bright','Deep and high-contrast']],
    ['hair','How deep is your natural hair?',['Light','Medium','Deep']],
    ['white','Which white works better near your face?',['Bright white','Soft cream','Both']]
  ];
  return '<div class="quiz-choice"><section><h2>Use one selfie</h2><p>Your photo stays on this device until you consent. The analysis API endpoint is awaiting founder configuration, so the visual quiz is the live web path.</p><label class="upload-box"><input id="selfie" type="file" accept="image/*"/>Choose a clear selfie</label><label><input id="photo-consent" type="checkbox"/> I consent to analysis when the endpoint is enabled.</label><output id="photo-preview"></output></section><form id="color-quiz"><h2>Or answer six visual questions</h2>'+qs.map((q,i)=>'<fieldset><legend>'+(i+1)+'. '+q[1]+'</legend>'+q[2].map((a,j)=>'<label><input required type="radio" name="'+q[0]+'" value="'+j+'"/> '+a+'</label>').join('')+'</fieldset>').join('')+'<button class="button" type="submit">See my season</button></form></div>';
}

async function main() {
  await rm(out, {recursive:true, force:true});
  await mkdir(join(out,'assets'), {recursive:true});
  await cp(join(root,'assets'), join(out,'assets'), {recursive:true});
  await cp(join(root,'styles.css'), join(out,'styles.css'));
  await cp(join(root,'pages.css'), join(out,'pages.css'));
  await cp(join(root,'site.js'), join(out,'site.js'));
  await cp(join(root,'favicon.svg'), join(out,'favicon.svg'));
  await writeFile(join(out,'CNAME'), new URL(SITE_URL).hostname + '\n');
  await QRCode.toFile(join(out,'assets','qr-download.png'), SITE_URL+'/download/', {width:336,margin:2,color:{dark:'#09090d',light:'#ffffff'}});
  const home = await readFile(join(root,'index.html'),'utf8');
  await writeRoute({path:'/',html:home});

  for (const f of featurePages) await writeRoute({path:f[0],title:f[1],h1:f[2],primaryKeyword:f[3],description:f[4],answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) includes this feature. '+f[4],image:f[5],imageAlt:f[2]+' in Style BFF',sections:f[6],faq:commonFaq,schema:{'@type':'WebPage','name':f[2]}});
  for (const page of standardPages) await writeRoute(page);

  await writeRoute({path:'/compare/',title:'Best AI Stylist App Comparison | Style BFF',h1:'The best AI stylist apps, compared honestly',primaryKeyword:'best ai stylist app',description:'Compare AI stylist apps by price, platform, color analysis, closet tools, daily outfits, and virtual try-on type.',answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) is one option in a broad styling category. The right app depends on whether you need closet tracking, color analysis, daily outfits or visual try-on.',sections:[['How should you compare AI stylist apps?','Start with the job you repeat most. Then verify platform, price, try-on type, closet setup and whether recommendations use your real clothes.'],['Which comparisons are ready?','Read the source-linked comparisons below. Prices and capabilities change, so every claim should be checked against the dated source.']],html:'<div class="link-grid">'+compareData.map(c=>'<a href="/compare/'+c[0]+'/">Style BFF vs '+esc(c[1])+' <span>↗</span></a>').join('')+'</div>',schema:{'@type':'ItemList','name':'AI stylist app comparisons','itemListElement':compareData.map((c,i)=>({'@type':'ListItem','position':i+1,'url':url('/compare/'+c[0]+'/')}))}});
  for (const [slug,name,href,verdict] of compareData) {
    const outline = slug.includes('indyx') || slug.includes('acloset');
    const h1 = slug === 'doppl-alternatives' ? 'Doppl is gone. Here are 7 alternatives.' : slug === 'chatgpt-as-a-stylist' ? 'ChatGPT as your stylist vs Style BFF' : 'Style BFF vs '+name;
    await writeRoute({path:'/compare/'+slug+'/',title:(slug==='doppl-alternatives'?'Doppl Alternatives':name+' Alternative')+' | Style BFF',h1,primaryKeyword:slug==='doppl-alternatives'?'doppl alternative':name.toLowerCase()+' alternative',description:'Compare Style BFF and '+name+' using current official sources, including core features, platform, try-on approach, closet tools, and price.',answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) '+verdict[0].toLowerCase()+verdict.slice(1),cite:verdict,sections:[['Which should you choose?','Choose '+name+' when its current official feature set best matches your main task. Choose Style BFF when you want a Style Profile, daily outfits and link-to-try-on centered on your own photo.'],['What do users say?','Public review quotations are intentionally omitted until the founder approves exact, fairly contextualized excerpts.']],html:comparisonHtml(name,href),faq:[['Is '+name+' the same as Style BFF?','No. They are separate products with different workflows and feature emphasis.'],['Which app uses my own clothes?','Style BFF includes a digital closet. Verify '+name+' against its current official source.'],['Which app has virtual try-on?','Style BFF renders outfits on your uploaded photo. Verify the current '+name+' listing for its try-on approach.'],['Which app is cheaper?','Style BFF publishes its US prices here. Check '+name+' at purchase time because store prices can change.'],['How recent is this comparison?','It was last reviewed on '+LAST_UPDATED+'.']],status:outline?'outline':'published',schema:{'@type':'Article','headline':h1,'dateModified':LAST_UPDATED,'author':{'@type':'Organization','name':'Style BFF editorial team'}}});
  }

  await writeRoute({path:'/answers/',title:'AI Stylist Questions Answered | Style BFF',h1:'Straight answers about AI styling',primaryKeyword:'ai stylist questions',description:'Get concise answers about AI stylists, virtual try-on, color analysis, digital closets, privacy, and Style BFF.',answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) answers common styling questions in short, source-ready pages. Start with the question that matches the decision you are making.',html:'<div class="link-grid">'+questions.map(q=>'<a href="/answers/'+slugify(q)+'/">'+esc(q)+' <span>↗</span></a>').join('')+'</div>',sections:[['How are these answers written?','Each page starts with the direct answer, adds practical context and links to related feature, comparison and guide pages.']],schema:{'@type':'FAQPage','mainEntity':questions.slice(0,10).map(q=>({'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':directAnswers[q]||'A source-reviewed answer is in preparation.'}}))}},'answers');
  for (let i=0;i<questions.length;i++) {
    const q = questions[i];
    const answer = directAnswers[q] || 'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) is preparing a source-reviewed answer to this question. The editorial outline is available while facts and product details are verified.';
    await writeRoute({path:'/answers/'+slugify(q)+'/',title:(q.replace('?','')+' | Style BFF').slice(0,60),h1:q,primaryKeyword:q.toLowerCase().replace('?',''),description:'Get a direct, practical answer to “'+q+'” with related Style BFF guides and current product context.',answer,sections:[['What is the useful detail?','The answer depends on whether you need advice, wardrobe organization, color analysis or a visual try-on. Check the current product page before making a paid decision.'],['What should you read next?',['<a href="/features/virtual-try-on/">Virtual try-on</a>','<a href="/compare/">Compare AI stylist apps</a>','<a href="/blog/seasonal-color-analysis-explained/">Color analysis guide</a>']]],status:i<10?'published':'outline',schema:{'@type':'QAPage','mainEntity':{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':answer}}}},'answers');
  }

  await writeRoute({path:'/blog/',title:'AI Styling Guides | Style BFF',h1:'The Style BFF blog',primaryKeyword:'ai styling guides',description:'Find practical Style BFF guides to color analysis, body type, daily outfits, digital closets, virtual try-on, and smarter shopping.',answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) publishes source-backed guides about getting dressed, using your closet and evaluating styling technology.',sections:[['What can you read now?','The seasonal color analysis pillar is available as an editorial outline. More articles remain hidden from search until founder-reviewed and published.']],html:'<div class="link-grid"><a href="/blog/seasonal-color-analysis-explained/">Seasonal color analysis, explained: all 12 seasons <span>↗</span></a></div>',schema:{'@type':'Blog','name':'The Style BFF blog'}},'blog');
  await writeRoute({path:'/blog/seasonal-color-analysis-explained/',title:'Seasonal Color Analysis Guide | Style BFF',h1:'Seasonal color analysis, explained: all 12 seasons',primaryKeyword:'seasonal color analysis',description:'Use this editorial outline for a sourced guide to hue, value, chroma, all 12 color seasons, self-testing, mistakes, palettes, and FAQs.',answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) uses seasonal color analysis to translate hue, value and chroma into a practical palette. This page is an editorial outline pending sourced prose.',cite:'Seasonal color analysis organizes personal coloring through temperature, depth and clarity. A useful result should change what you do with clothes, not stop at a palette label.',sections:[['What are hue, value and chroma?',['Define temperature and undertone.','Explain light-to-deep value.','Explain soft-to-bright chroma.']],['What are the 12 seasons?',['Spring: bright, true, light.','Summer: light, true, soft.','Autumn: soft, true, deep.','Winter: deep, true, bright.']],['How can you find your season?',['Compare in-person draping with image analysis.','List lighting and camera mistakes.','Show what to do with the palette.']]],status:'outline',schema:{'@type':'BlogPosting','headline':'Seasonal color analysis, explained: all 12 seasons','dateModified':LAST_UPDATED,'author':{'@type':'Organization','name':'Style BFF editorial team'}}},'blog');

  await writeRoute({path:'/glossary/',title:'Personal Styling Glossary | Style BFF',h1:'The personal styling glossary',primaryKeyword:'personal styling terms',description:'Look up clear definitions for color seasons, Kibbe types, undertone, chroma, capsule wardrobes, cost per wear, and virtual try-on.',answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) defines the language used in color analysis, body proportion, wardrobes and virtual try-on in one plain-English glossary.',html:'<div class="link-grid">'+glossary.map(term=>'<a href="/glossary/'+slugify(term)+'/">'+esc(term)+' <span>↗</span></a>').join('')+'</div>',sections:[['How should you use this glossary?','Read the one-sentence definition first, then follow the related feature and answer pages for practical detail.']],schema:{'@type':'DefinedTermSet','name':'Style BFF personal styling glossary'}},'glossary');
  for (const term of glossary) await writeRoute({path:'/glossary/'+slugify(term)+'/',title:(term+' Meaning | Style BFF').slice(0,60),h1:term,primaryKeyword:term+' meaning',description:'Learn the meaning of '+term+' and how it relates to personal styling, outfits, wardrobes, color analysis, or virtual try-on.',answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) defines '+term+' as a practical styling term. This concise definition is pending specialist review before publication.',sections:[['How is '+term+' used in styling?','Use the concept as one input, then connect it to your colors, proportions, clothes and real plans.'],['What should you read next?',['<a href="/features/color-analysis/">Color analysis</a>','<a href="/answers/what-is-an-ai-personal-stylist/">AI stylist answer</a>','<a href="/blog/seasonal-color-analysis-explained/">Seasonal color guide</a>']]],status:'outline',schema:{'@type':'DefinedTerm','name':term,'description':'A personal styling term awaiting specialist-reviewed definition.'}},'glossary');

  const faq25 = [
    ['What is Style BFF?','An AI personal stylist that learns your profile and shows outfits on your own photo.'],['How is an outfit rendered on me?','Upload a clear photo and choose or receive a look to preview.'],['What photo should I upload?','Use a clear, well-lit, unfiltered, front-facing or full-length photo.'],['How accurate is virtual try-on?','It is a styling preview, not a guarantee of fit or garment detail.'],['What does the Style Profile include?','A color season, body type and three personal style rules.'],['Is the Style Profile really free?','Yes, and it does not require a card.'],['How is my daily outfit chosen?','From your profile, preferences, context and closet inputs.'],['Can I add my own clothes?','Yes.'],['Does it work for men?','Current model coverage needs founder confirmation before launch.'],['Does it work for plus sizes?','The product is designed around proportion; current coverage needs founder confirmation.'],['Does it support hijab or modest dressing?','Preference controls and current model coverage need founder confirmation.'],['Which countries and currencies are supported?','The product targets the US, UK, Canada and Australia; local store availability and currency apply.'],['How do I cancel?','Cancel in Apple Subscriptions or Google Play Subscriptions.'],['Can I get a refund?','Refund decisions follow the store policy where you paid.'],['Are there student discounts?','No discount is published until the founder confirms one.'],['What happens to my photos?','The final privacy policy must state processing and retention details before launch.'],['Are photos used to train models?','This answer awaits founder and counsel confirmation.'],['How do I delete my account?','Use the in-app setting or the delete-account page.'],['Can I export my data?','Export availability and process await founder confirmation.'],['Is BingeTry the same app?','Yes. Style BFF is the new name for BingeTry.'],['Why did the name change?','The product grew from try-on into an everyday personal stylist.'],['Who built Style BFF?','Founder names and bios await approval.'],['What is on the roadmap?','Hair, makeup and jewelry matching are marked coming soon.']
  ];
  await writeRoute({path:'/faq/',title:'Style BFF FAQ | Style BFF',h1:'Questions, answered',primaryKeyword:'style bff faq',description:'Read answers about Style BFF features, photos, accuracy, free profile, cancellation, privacy, BingeTry, and the roadmap.',answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) answers product, privacy and brand questions below. Unconfirmed founder and legal details are clearly marked instead of guessed.',faq:faq25,schema:{'@type':'WebPage','name':'Style BFF frequently asked questions'}});

  await writeRoute({path:'/quiz/',title:'Color Season Quiz | Style BFF',h1:'What’s your color season?',primaryKeyword:'color season quiz',description:'Take a free six-question color season quiz, or choose a selfie for local preview, then see a shareable palette and outfit formulas.',answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) offers a free visual color-season quiz. Answer six questions to get a starting season, then use the app for a selfie-based Style Profile.',html:quizHtml(),sections:[['What will the result include?','A 12-season starting point, palette swatches and three outfit formulas. Results are guidance, not a professional draping diagnosis.']],schema:{'@type':['Quiz','WebApplication'],'name':'Style BFF color season quiz'}});
  for (const season of seasons) await writeRoute({path:'/quiz/result/'+season+'/',title:season.replaceAll('-',' ').replace(/\b\w/g,c=>c.toUpperCase())+' Color Palette | Style BFF',h1:season.replaceAll('-',' ').replace(/\b\w/g,c=>c.toUpperCase())+' color palette',primaryKeyword:season.replaceAll('-',' ')+' color palette',description:'See a '+season.replaceAll('-',' ')+' color palette, practical neutrals, three outfit formulas, and the next step for a Style BFF selfie analysis.',answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) uses '+season.replaceAll('-',' ')+' as one of 12 seasonal palettes. Use this result as a starting point and check colors near your face in consistent daylight.',html:'<div class="palette" data-season="'+season+'"><span></span><span></span><span></span><span></span><span></span><span></span></div><div class="formula-grid"><article><h3>Formula one</h3><p>Core neutral + best light + focused accent.</p></article><article><h3>Formula two</h3><p>Tonal column + metallic detail + quiet shoe.</p></article><article><h3>Formula three</h3><p>Denim + near-face color + repeated accessory.</p></article></div><form class="email-form" data-email-capture><label>Email my palette <input type="email" required placeholder="you@example.com"/></label><button class="button" type="submit">Save my palette</button><output></output></form>',sections:[['How should you use this palette?','Keep the strongest colors near your face, repeat one accent elsewhere and compare options in the same light.']],schema:{'@type':'WebPage','name':season+' color palette'}});

  await writeRoute({path:'/download/',title:'Download Style BFF | Style BFF',h1:'Get Style BFF',primaryKeyword:'download style bff',description:'Download Style BFF for iPhone or Android. Desktop visitors can scan a QR code; campaign parameters are passed to the appropriate store.',answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) is available from the App Store and Google Play. Mobile visitors are sent to the matching store; desktop visitors can choose.',html:'<div class="download-panel" data-download-page>'+storeButtons('download')+'<p>Campaign parameters are preserved when supported by the destination store.</p></div>',sections:[['Which device is supported?','Style BFF is available for iPhone and Android.']],schema:{'@type':'SoftwareApplication','name':'Style BFF','operatingSystem':'iOS, Android','applicationCategory':'LifestyleApplication','downloadUrl':[APP_STORE_URL,PLAY_STORE_URL]}});
  for (const [preset,ppid] of [['color',COLOR_CPP_ID],['tryon',TRYON_CPP_ID],['closet',CLOSET_CPP_ID]]) await writeRoute({path:'/download/'+preset+'/',title:'Download Style BFF for '+preset+' | Style BFF',h1:'Get Style BFF',primaryKeyword:'download style bff',description:'Download Style BFF for '+preset+' on iPhone or Android using a campaign-ready store link.',answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) opens the right store for your device. This '+preset+' preset is ready for its founder-supplied Apple product-page ID.',html:'<div class="download-panel" data-download-page data-preset="'+preset+'" data-ppid="'+ppid+'">'+storeButtons('download-'+preset)+'</div>',schema:{'@type':'SoftwareApplication','name':'Style BFF','operatingSystem':'iOS, Android'}});

  await writeRoute({path:'/sitemap/',title:'HTML Sitemap | Style BFF',h1:'Find every Style BFF page',primaryKeyword:'style bff sitemap',description:'Browse Style BFF product, comparison, answer, blog, glossary, company, support, and legal pages from one human-readable sitemap.',answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) groups its public pages below so people and search engines can reach every published resource.',html:'<div class="link-grid" id="html-sitemap"></div>',sections:[['What is included?','Published product, company, comparison, answer, blog and glossary pages. Editorial outlines remain out of the XML sitemap.']]});
  await writeRoute({path:'/contact/',title:'Support | Style BFF',h1:'Redirecting to Support',primaryKeyword:'support',description:'Redirecting to Style BFF support.',answer:'Redirecting to Style BFF support.',html:'<script>location.replace("/support/");</script><p><a href="/support/">Click here to open Support</a></p>',noSitemap:true});

  const notFoundHtml = '<script>(function(){var p=location.pathname.replace(/\\/+$/,"");var r={"/contact":"/support/","/features":"/features/daily-outfits-on-you/","/style-feed":"/features/daily-outfits-on-you/","/glow-feed":"/features/daily-outfits-on-you/","/lookbook":"/features/digital-closet/","/glowbook":"/features/digital-closet/","/how-it-works":"/how-it-works/"};if(r[p]){location.replace(r[p]);}})();</script><form action="/blog/" method="get" class="search-form"><label>Search the blog <input type="search" name="q"/></label><button class="button">Search</button></form>';
  await writeRoute({path:'/404/',title:'Page Not Found | Style BFF',h1:'That look left the closet',primaryKeyword:'page not found',description:'The requested Style BFF page was not found. Search the blog or use the top links to continue.',answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) could not find this page. Try the blog, features or download page.',html:notFoundHtml,noSitemap:true});
  await cp(join(out,'404','index.html'), join(out,'404.html'));

  for (const p of ['/try/','/r/','/look/']) await writeRoute({path:p,title:'Open in Style BFF | Style BFF',h1:'Open this in Style BFF',primaryKeyword:'open style bff',description:'Open this Style BFF link in the iOS or Android app, or continue to the matching store when the app is not installed.',answer:'Style BFF (AI personal stylist and virtual try-on app for iOS and Android) uses this link to open the app when installed. If it does not open, continue to the download page.',html:'<p><a class="button" href="/download/">Continue to download</a></p>',noSitemap:true});

  const xml = paths => '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+paths.map(p=>'<url><loc>'+url(p)+'</loc><lastmod>'+LAST_UPDATED+'</lastmod></url>').join('')+'</urlset>';
  await mkdir(join(out,'sitemaps'),{recursive:true});
  for (const [group,paths] of Object.entries(sitemapGroups)) await writeFile(join(out,'sitemaps',group+'.xml'),xml(paths));
  await writeFile(join(out,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+Object.keys(sitemapGroups).map(g=>'<sitemap><loc>'+SITE_URL+'/sitemaps/'+g+'.xml</loc></sitemap>').join('')+'</sitemapindex>');
  await writeFile(join(out,'robots.txt'),'User-agent: *\nAllow: /\n\nUser-agent: GPTBot\nAllow: /\nUser-agent: ChatGPT-User\nAllow: /\nUser-agent: OAI-SearchBot\nAllow: /\nUser-agent: PerplexityBot\nAllow: /\nUser-agent: ClaudeBot\nAllow: /\nUser-agent: Google-Extended\nAllow: /\nUser-agent: Bingbot\nAllow: /\nUser-agent: Applebot\nAllow: /\n\nSitemap: '+SITE_URL+'/sitemap.xml\n');
  const llms = '# Style BFF\n\nStyle BFF is an AI personal stylist app for iOS and Android that renders daily outfits on the user\'s own photo, builds a free Style Profile, styles an owned closet and supports link-to-try-on.\n\n- [Press]('+SITE_URL+'/press/): Verified product facts and citation language.\n- [How it works]('+SITE_URL+'/how-it-works/): The six-step styling loop.\n- [Compare]('+SITE_URL+'/compare/): Source-linked app comparisons.\n- [Answers]('+SITE_URL+'/answers/): Direct answers about AI styling.\n- [FAQ]('+SITE_URL+'/faq/): Product, privacy and brand questions.\n';
  await writeFile(join(out,'llms.txt'),llms);
  await writeFile(join(out,'llms-full.txt'),llms+'\n## FAQ\n'+faq25.map(x=>'### '+x[0]+'\n'+x[1]).join('\n\n')+'\n\n## Answers\n'+questions.map(q=>'### '+q+'\n'+(directAnswers[q]||'Editorial outline pending source review.')).join('\n\n'));
  await writeFile(join(out,'rss.xml'),'<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>The Style BFF blog</title><link>'+SITE_URL+'/blog/</link><description>Practical AI styling guides.</description></channel></rss>');
  await mkdir(join(out,'.well-known'),{recursive:true});
  await writeFile(join(out,'.well-known','apple-app-site-association'),JSON.stringify({applinks:{details:[{appIDs:[APPLE_TEAM_ID+'.com.bingetry.vitualtryon'],components:[{'/':'/try/*'},{'/':'/r/*'},{'/':'/quiz/*'},{'/':'/download/*'},{'/':'/look/*'}]}]}}));
  await writeFile(join(out,'.well-known','assetlinks.json'),JSON.stringify([{relation:['delegate_permission/common.handle_all_urls'],target:{namespace:'android_app',package_name:'com.bingetry.vitualtryon',sha256_cert_fingerprints:[ANDROID_SHA256]}}]));
  await writeFile(join(out,'redirects.map.txt'),'/#features /features/daily-outfits-on-you/ 301\n/#style-feed /features/daily-outfits-on-you/ 301\n/#glow-feed /features/daily-outfits-on-you/ 301\n/#lookbook /features/digital-closet/ 301\n/#glowbook /features/digital-closet/ 301\n/#how-it-works /how-it-works/ 301\n/contact /support/ 301\n');
  const allLinks = [...allPaths].filter(p=>!p.includes('/404/')).sort();
  const sitemapFile = join(out,'sitemap','index.html');
  const sitemapHtml = await readFile(sitemapFile,'utf8');
  await writeFile(sitemapFile,sitemapHtml.replace('<div class="link-grid" id="html-sitemap"></div>','<div class="link-grid">'+allLinks.map(p=>'<a href="'+p+'">'+p+' <span>↗</span></a>').join('')+'</div>'));
  console.log('Built '+allPaths.size+' routes into dist.');
}

await main();
